### ISSUE TITLE
Show City/Country instead of Village/Hospital for birth and death 

### ISSUE THREAD

**Issue by mshd** [dataprick/wikitree#15]
This is a bit of a tricky task. As you see Barack Obama ([tree](http://localhost:3000/?q=Q76&level=2&type=ancestors&orientation=North&lang=en&options%5Bsocialmedia%5D=on) was born in 
Kapiolani Medical Center for Women and Children.
Nobody cares about the hospital, they value in need in Honolulu or Hawaii.
Now we need to make another request to see if the birth place is not a locality (or a hospital). That is possible by using P31 (instance of). Then get the label for the property 
**located in the administrative territorial entity** [P131](https://www.wikidata.org/wiki/Property:P131) or **location** [P276](https://www.wikidata.org/wiki/Property:P276)

I also don't know what's the best way to tackle it.

**Comment by edwinindrajayas** [comment]
By calling callback from different route depends on if there is place with instance of hospital.
First, populate the place of birth and place of death Ids in the each node to the array that will be checked on the last iteration callback.
After that, check if there is label that is an instance of hospital, then call the API and wait for the response using async await Promise before calling callback function.
if it's not instance of hospital then process the label and callback as usual
