### ISSUE TITLE
Add support for dates without day or month

### ISSUE THREAD

**Issue by mshd** [dataprick/wikitree#18]
https://github.com/dataprick/wikitree/blob/3e4e812c82f6d4e13a08c0f712c3c0433ea3db2b/controllers/processNode.js#L124

Before I was using moment.js for date using `function parseDate(unformattedDate){` still existing in the file. Wikidata-sdk has a date handler, find out if it's useful. We might still need moment.js (but it just supports normal dates)
It should support:

- [x] Full dates 

- [x] Full dates should be displayed using momentJS

- [x] Dates with only month 1990-11

- [x] Only years 1990

- [x] BCE years (-4) or 4 BCE

Addition:

- [x] Make sure sorting works, this is important for the descendants view, so the children are in order, it can be a string or timestamp. 

Reference for sorting
https://github.com/dataprick/wikitree/blob/012a896e96f6ebebb883bec20c2e6265860dd2f3/public/js/treant-wikidata.js#L33-L37

**Comment by edwinindrajayas** [comment]
From the docs, it seems that the function wikibaseTimeToSimpleDay wikidata-sdk provided can only meet the three criteria
Full dates ('yyyy-mm-dd'),
Dates with only month ('yyyy-mm') 
and  Only years ('yyyy').

for the BCE, we can use the other function wikidata-sdk provided (wikibaseTimeToISOString)

Source: 
wikibaseTimeToISOString
https://github.com/maxlath/wikibase-sdk/blob/master/docs/general_helpers.md#wikibasetimetoisostring

wikibaseTimeToSimpleDay
https://github.com/maxlath/wikibase-sdk/blob/master/docs/general_helpers.md#wikibasetimetosimpleday

**Comment by mshd** [comment]
Ok, let's implement it. wikibaseTimeToSimpleDay is returning 1990-01-01, even though it should be 1990

**Comment by mshd** [comment]
Good, please check the boxes in the issue text, when you're done
