### ISSUE TITLE
Change the data structure to support Siblings and Spouses/Partner

### ISSUE THREAD

**Issue by mshd** [dataprick/wikitree#23]
Subissue of #6

[result2.zip](https://github.com/dataprick/wikitree/files/4612203/result2.zip) see basic-example.js

I have found someone to update TreantJS, attached is an example. 
The new data structure has a new element called "spouse". We can get the property spouse, but this will not be enough, as some people have children with other people :)
Basically we need to get the children first and see what their other father/mother for an element has. Addition recursive functions are needed.

1. change Treant.js to TreantSpouse.js (file already in Rep) only for testing
2. see example zip for the new data structure, 
3. !!!! first level **cannot** have a spouse, so please start after the second level
4. if you get stuck, continue another Issue.

- [x] Add spouse from property "spouse"

- [ ] Add spouse from children's "other parent"

- [x] Add siblings (later)

The Plugin might still be buggy, but we need to test it with our tool

**Comment by edwinindrajayas** [comment]
Hi @mshd .  I don't know if that's is correct. After i get the id for the spouse, i call the api through Axios, but the curly bracket that usually change into value is not working

**Comment by mshd** [comment]
Yes, that is certainly not correct, first of all: don't use axios.get(), we already have a function for this that does the same "wikidataController.wikidataApi"
As you can see in the page, it's not showing anything. A spouse can have children, a spouse can not have another spouse. Further, these are callback functions so you need some new function/structure.

**Comment by edwinindrajayas** [comment]
![Capture](https://user-images.githubusercontent.com/63530715/81921844-cf9aee80-960d-11ea-936b-17d20035d6b7.GIF)

Okay, i'll remove the axios tomorrow, i just realized that wikidatacontroller.wikidataApi after pushed. So, in the screenshot that i attached, so later every entity either the husband or the wife have their own children, is that what you mean?

**Comment by mshd** [comment]
Yes that looks good, but keep in mind, that there can be multiple spouses. The children always go down from the spouse, your added hand-drawing is not necessary. Please push these chaanges

**Comment by mshd** [comment]
Please keep, in mind that data structure is only for descendants, for ancestors, nothing should be changed

**Comment by mshd** [comment]
Idea: first just work on descandants without spouses, save all spouses in an array.
In all children add "mother" and "father" value to the array. Remove existing ids from the spouses (becuase either mother or father is already within the tree). Reconstruct the tree hierarchy. Add spouses or other parent to the structure, the unflatten function may also be moved to the backend

**Comment by mshd** [comment]
@edwinindrajayas for siblings you need to add a pseudo node
[JSON data structure guide.docx](https://github.com/dataprick/wikitree/files/4707545/JSON.data.structure.guide.docx)

**Comment by mshd** [comment]
![Screenshot from 2020-05-31 13-30-37](https://user-images.githubusercontent.com/17379661/83351289-f01fb400-a342-11ea-8395-55284e5e315f.png)
