### ISSUE TITLE
Error too much recursion

### ISSUE THREAD

**Issue by mshd** [dataprick/wikitree#44]

**Comment by mshd** [comment]
https://tools.wmflabs.org/wikioverdata/wikitree/public/?q=Q504998&level=5&type=owns&orientation=North&lang=en

**Comment by edwinindrajayas** [comment]
@mshd, the main problem for this case is because there is parent id which listed on the child of the tree, so the recursive is caught in infinite loop. So we need to remove the duplicate row data
