### ISSUE TITLE
Error processing data, please try again

### ISSUE THREAD

**Issue by johnsamuelwrites** [dataprick/wikitree#55]
I was exploring 'Ancestors' on Wikitree, with different persons. The resulting visualization for most cases were fine. However, I get the following error:

`Error processing data, please try again` for the URL

https://tools.wmflabs.org/wikioverdata/wikitree/public/?q=Q302&level=2&type=ancestors&type_label=ancestors&orientation=North&lang=en

Checking the console, I see these errors:
```
 Sibling EXIST for Q302 , sibling count is  1 on level 2 bundle.js:874:17
ERROR fetch in Wikidata.js :invalid entity id: undefined
```

**Comment by mshd** [comment]
Thank you for reporting @johnsamuelwrites 
Reason: Unknown/NoValue for deathPlace ([example](https://www.wikidata.org/wiki/Q345#P20))
Fix: remove undefined, remove unknown/NoValue
