### ISSUE TITLE
Add Wikitree api image

### ISSUE THREAD

**Issue by mshd** [dataprick/wikitree#9]
https://api.wikitree.com/api.php?action=getProfile&key=Von_Amsberg-2
if Wikitree property is set and images is empty try to fetch a image from Wikitree
using a nodeJS equivilant to `json_decode(file_get_contents("https://api.wikitree.com/api.php?".http_build_query($_GET)));`

**Comment by edwinindrajayas** [comment]
Check the new created node if there is no images and fetch from Wikitree API

**Comment by mshd** [comment]
Before you code please check my previous commit, I already implemented a function in an extra file. Please change that function, and add the changes to processNode
